### ISSUE TITLE
The PHP bootstrap script for the Sqon does not have a shebang line.

### ISSUE THREAD

**Issue by AnthonyPorthouse** [Sqon/sqon#4]
## Problem

Sqon files currently have issues with shebangs.

Newly created files are created without shebangs (meaning it cannot simply be made executable and ran) and any shebangs in a file such as

``` php
#!/usr/bin/env php
<?php
require_once __DIR__ . '/../vendor/autoload.php';
```

are simply echoed out into the terminal.
## Resolution

I believe a suitable solution for this would be to prepend Sqon output with a shebang and strip a shebang from any primary files if they are found.

**Comment by kherge** [comment]
I think there may be a misunderstanding on how the shebang line works in Sqon packages.

To add a shebang line to a Sqon, you will need to change the [bootstrap script](https://github.com/Sqon/sqon#bootstrap) to include one. Fortunately, this is simple enough with the current API:

``` php
use Sqon\Sqon;

$sqon->setBootstrap(Sqon::createBootstrap('#!/usr/bin/env php'));
```

As you have noticed, the real problem is with scripts that already have the shebang line added. At this time I have no intention to include any file processing capabilities directly to this particular library (aside from compression), but I am considering creating a new library with utilities for this type of use case. I am open to suggestions on how this library can be modified to make it easier to integrate third-party code.

**Comment by kherge** [comment]
So, I changed my mind. 😁 

The Sqon manager can now accept an event dispatcher to modify the Sqon building process. I included some pretty basic ones with the library, one of which being the `ReplaceSubscriber`. Here's an example of how you can use `ReplaceSubscriber` to remove the shebang line from a script.

``` php
use Sqon\Event\Subscriber\ReplaceSubscriber;
use Sqon\Path\File;
use Sqon\Sqon;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

// Create the new manager.
$sqon = Sqon::create('example.sqon');

// Register an event dispatcher to enable build customization.
$dispatcher = new EventDispatcher();

$sqon->setEventDispatcher($dispatcher);

// Now register the replace subscriber to remove the shebang line from a script.
$dispatcher->addSubscriber(
    new ReplaceSubscriber(
        [
            'files' => [
                'bin/console' => [
                    '/^#![^\n\r]+[\n\r]+/m' => ''
                ]
            ]
        ]
    )
);

// Set the path that has the shebang line.
$sqon->setPath('bin/console', new File('/path/to/console/script'));

// Do other stuff you need.
```

Now when you run the Sqon, the shebang line should no longer be present.

For more examples, you can see the [Event Subscribers](https://github.com/Sqon/sqon#event-subscribers) section of the README.

**Comment by AnthonyPorthouse** [comment]
:+1: this makes sense, I'll try and get a chance to try it out again in the next few days. Thanks for this!

**Comment by kherge** [comment]
I'm looking at reviving this project so I'm cleaning house. It's been almost 4 years, so I'll close the issue.
